# Generated by Django 5.0.2 on 2024-02-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todouser',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='todouser',
            name='list_count',
            field=models.IntegerField(default=0),
        ),
    ]
